apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: helloworld
  namespace: fluxcd-poc-dev1-platform
spec:
  interval: 1m
  approvePlan: auto
  # path: ./clusters/infra/tf-modules
  storeReadablePlan: json
  sourceRef:
    kind: GitRepository
    name: flux-tf-helloworld
    namespace: fluxcd-poc-dev1-platform
  writeOutputsToSecret:
    name: helloworld-output
